services:
  App\Command\AbstractCommand:
    abstract: true
    calls:
      - [setLogExtraDataKeeper, ['@Ewll\LogExtraDataBundle\LogExtraDataKeeper']]

  App\Command\UpdateDepoolsListCommand:
    parent: App\Command\AbstractCommand
    arguments:
      - '@logger'
      - '@doctrine.orm.entity_manager'
      - '@App\Ton'
    tags:
      - { name: 'console.command', command: 'depool:list:update' }

  App\Command\AppendDepoolRoundCommand:
    parent: App\Command\AbstractCommand
    arguments:
      - '@logger'
      - '@doctrine.orm.entity_manager'
      - '@App\Ton'
    tags:
      - { name: 'console.command', command: 'depool:rounds:append' }
