apiVersion: v1
kind: Service
metadata:
    name: depool-nginx
spec:
    ports:
        -   port: 80
            targetPort: 80
            protocol: TCP
            name: http
    selector:
        app: depool-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: depool-nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: depool-nginx
    template:
        metadata:
            labels:
                app: depool-nginx
        spec:
            containers:
                -   name: depool-nginx
                    image: extraton/depool-dashboard:0.1.11
                    ports: [{containerPort: 80}]
                    command: ['/bin/bash']
                    args: ['-c', "php-fpm --nodaemonize & nginx -g 'daemon off;'"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: depool-cron
spec:
    replicas: 1
    selector:
        matchLabels:
            app: depool-cron
    template:
        metadata:
            labels:
                app: depool-cron
        spec:
            containers:
                -   name: depool-cron
                    image: extraton/depool-dashboard:0.1.11
                    command: ['/bin/bash']
                    args: ['-c', "crontab /var/www/html/config/cron && crond -n"]
