ewll_crud:
  resource: '@EwllCrudBundle/Resources/config/routing.yaml'
  prefix: '/crud'

index:
  path: /{route}
  controller: App\Controller\IndexController::index
  methods: [GET]
  requirements: {route: '^.+'}
  defaults: {route: null}
