api.depools:
  path: /api/depools
  controller: App\Controller\IndexController::depools
  methods: [GET]

index:
  path: /{route}
  controller: App\Controller\IndexController::index
  methods: [GET]
  requirements: {route: '^.+'}
  defaults: {route: null}
